spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:50201/pharmacy
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration